# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--safe]
      - id: black-jupyter
        args: [--safe]

  - repo: https://github.com/janosh/format-ipy-cells
    rev: v0.1.7
    hooks:
      - id: format-ipy-cells

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
